apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: vue-laravel-k8s
build:
  artifacts:
  - image: puzon103/laravel
    docker:
      dockerfile: laravel/Dockerfile
  - image: puzon103/vue
    docker:
      dockerfile: vue/Dockerfile
manifests:
  kustomize:
    paths:
      - "k8s"