apiVersion: skaffold/v3
kind: Config
metadata:
  name: vue-laravel-k8s
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  artifacts:
  - image: puzon103/laravel
    docker:
      dockerfile: laravel/Dockerfile
  - image: puzon103/vue
    docker:
      dockerfile: vue/Dockerfile
manifests:
  kustomize:
    paths:
      - "k8s"