apiVersion: v1
kind: Service
metadata:
  namespace: vue-laravel-k8s
  name: laravel-k8s-service
  labels:
    app: vue-laravel-k8s
spec:
  # type: LoadBalancer
  selector:
    app: laravel-app
  ports:
  - port: 80
    name: laravel
    targetPort: 80