name: Build image
on:
  push:
    branches:
      - "main"

jobs:
  pipeline:
    name: Skaffold Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Skaffold build
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: build
          repository: ghcr.io/${{ github.repository }}